import { StyleSheet } from "react-native";

const style = StyleSheet.create({
  background: {
    flex: 1,
    alignItems: "center",
  },
  registerForm: {
    marginTop: "30%",
    minHeight: 450,
    borderRadius: 20,
    backgroundColor: "#26262a",
    width: "80%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-around",
  },
  title: {
    height: "15%",
    color: "white",
    fontFamily: "Poppins",
    fontWeight: "800",
    textAlign: "center",
    textAlignVertical: "bottom",
    fontSize: 50,
  },
  formInput: {
    width: "70%",
    borderRadius: 50,
    textAlign: "center",
    fontSize: 19,
    color: "white",
    borderBottomColor: "white",
    borderWidth: 1,
  },
  registerFormButton: {
    width: "70%",
    borderRadius: 50,
    backgroundColor: "white",
    color: "black",
    borderBottomColor: "white",
    fontSize: 19,
    paddingHorizontal: 50,
    paddingVertical: 8,
  },
  registerRedirection: {
    backgroundColor: "white",
    width: 100,
    marginRight: 15,
    paddingHorizontal: 10,
    height: 30,
    borderBottomColor: "black",
    justifyContent: "center",
    borderRadius: 20,
    alignItems: "center",
  },
  loginForm: {
    marginTop: "30%",
    minHeight: 400,
    borderRadius: 20,
    backgroundColor: "#26262a",
    width: "80%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  InputPassword: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    paddingHorizontal: 10,
  },
  input: {
    flex: 1,
    height: 40,
  },
  toggleButton: {
    padding: 0,
  },
  toggleText: {
    color: "#007AFF",
    fontWeight: "bold",
  },
  subTitle: {
    height: "15%",
    color: "white",
    fontFamily: "Poppins",
    fontWeight: "800",
    textAlign: "center",
    textAlignVertical: "bottom",
    fontSize: 30,
  },
  textArea: {
    width: "80%",
    height: 100,
    borderWidth: 1,
    borderColor: "#ccc",
    fontSize: 19,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    color: "white",
    textAlignVertical: "top", // Alinea el texto arriba, como en un textarea
  },
  textTitle: {
    width: "80%",
    borderRadius: 8,
    textAlign: "center",
    fontSize: 19,
    color: "white",
    borderBottomColor: "white",
    borderWidth: 1,
  },
  generalScroll: { flexGrow: 1, alignItems: "center" },
  containerTask: {
    backgroundColor: "#26262a",
    height: 250,
    width: "80%",
    margin: 15,
    flexDirection: "column",
    padding: "5%",
    gap: 10,
    borderRadius: 20,
  },
  titleTask: {
    color: "white",
    fontSize: 30,
    alignSelf: "center",
  },
  descriptionTask: {
    color: "white",
    fontSize: 18,
  },
  checkBoxTask: {
    position: "absolute",
    right: "10%",
    bottom: "20%",
  },
});
export default style;
